Repository myelin-ai/engine, pull requests merged in 2019-03, with the labels that each got.

#58 Address geometry reviews
  geometry/src/vector.rs
Labels: refactoring

#53 Implement intersection check for polygon
  geometry/src/aabb.rs
  geometry/src/intersects.rs
  geometry/src/lib.rs
  geometry/src/polygon.rs
Labels: enhancement

#50 Support collision checks in areas defined by any convex polygon
  Cargo.lock
  engine/Cargo.toml
  engine/changelog.md
  engine/src/simulation.rs
  engine/src/simulation/simulation_impl.rs
  engine/src/simulation/simulation_impl/world.rs
  engine/src/simulation/simulation_impl/world/nphysics_world.rs
  geometry/Cargo.toml
  geometry/changelog.md
  geometry/src/aabb.rs
  geometry/src/polygon.rs
Labels: enhancement

#60 Add changelog to template
  .github/ISSUE_TEMPLATE/new-release.md
Labels: refactoring

#61 Extract geometry crate
  Cargo.lock
  Cargo.toml
  changelog.md
  coverage.sh
  engine/Cargo.toml
  geometry/Cargo.toml
  geometry/changelog.md
  geometry/src/aabb.rs
  geometry/src/convex_hull.rs
  geometry/src/intersects.rs
  geometry/src/lib.rs
  geometry/src/point.rs
  geometry/src/polygon.rs
  geometry/src/polygon/builder.rs
  geometry/src/radians.rs
  geometry/src/vector.rs
  src/lib.rs
  src/object.rs
  src/object/object_behavior.rs
  src/object_builder.rs
  src/prelude.rs
  src/simulation.rs
  src/simulation/simulation_impl.rs
  src/simulation/simulation_impl/builder.rs
  src/simulation/simulation_impl/time.rs
  src/simulation/simulation_impl/world.rs
  src/simulation/simulation_impl/world/nphysics_world.rs
  src/simulation/simulation_impl/world/nphysics_world/builder.rs
  src/simulation/simulation_impl/world/nphysics_world/physics_world_wrapper.rs
  src/simulation/simulation_impl/world/nphysics_world/rotation_translator.rs
  src/simulation/simulation_impl/world/nphysics_world/rotation_translator/rotation_translator_impl.rs
  src/world_interactor.rs
  src/world_interactor/interactable.rs
  src/world_interactor/world_interactor_impl.rs
  tests/smoke_test.rs
Labels: refactoring

#63 Allow more flexible object retrieval
  .gitignore
  Cargo.toml
  changelog.md
  src/object/object_behavior.rs
  src/simulation.rs
  src/simulation/simulation_impl.rs
  src/simulation/simulation_impl/builder.rs
  src/world_interactor.rs
  src/world_interactor/interactable.rs
  src/world_interactor/world_interactor_impl.rs
  tests/integration_tests.rs
  tests/smoke_test.rs
Labels: enhancement

#65 Expose interferences with polygon
  Cargo.toml
  changelog.md
  src/simulation.rs
  src/simulation/simulation_impl.rs
  src/simulation/simulation_impl/world.rs
  src/simulation/simulation_impl/world/nphysics_world.rs
  src/world_interactor.rs
  src/world_interactor/interactable.rs
  src/world_interactor/world_interactor_impl.rs
Labels: enhancement

#70 Implement raycasts
  Cargo.toml
  changelog.md
  src/simulation.rs
  src/simulation/simulation_impl.rs
  src/simulation/simulation_impl/world.rs
  src/simulation/simulation_impl/world/nphysics_world.rs
Labels: enhancement

#77 Expose ray casts
  src/simulation/simulation_impl.rs
  src/world_interactor.rs
  src/world_interactor/interactable.rs
  src/world_interactor/world_interactor_impl.rs
Labels: enhancement

#79 Release 0.8.0
  Cargo.toml
  changelog.md
Labels: enhancement

#81 Passable bodies
  changelog.md
  src/simulation/simulation_impl.rs
  src/simulation/simulation_impl/world.rs
  src/simulation/simulation_impl/world/nphysics_world.rs
Labels: bug

#84 Remove nphysics rotation translator
  src/simulation/simulation_impl.rs
  src/simulation/simulation_impl/world/nphysics_world.rs
  src/simulation/simulation_impl/world/nphysics_world/builder.rs
  src/simulation/simulation_impl/world/nphysics_world/rotation_translator.rs
  src/simulation/simulation_impl/world/nphysics_world/rotation_translator/rotation_translator_impl.rs
Labels: refactoring
